[package]
name = "inline-require"
authors = ["skay <skaypist@gmail.com>"]
version = "0.1.0"
homepage = "https://github.com/skaypist/inline-require"
repository = "https://github.com/skaypist/inline-require"
keywords = ["require"]


[dragonruby]
version = "2"
edition = "standard"
