[package]
name = "rspec-mruby"
authors = ["TODO <TODO@example.com>"]
version = "0.1.0"
homepage = "TODO: Package Website"
keywords = []

# Optional:
# documentation = "https://example.com"
# repository = "http://github.com/example/example"

# Which files do you want to be automatically required from your package.
requires = ["require-in-smaug.rb"]


[dragonruby]
version = "2"
edition = "standard"
